#!/bin/bash

alias ls='ls --color=auto'
alias l='ls -lAh'

alias files='xdg-open . &> /dev/null'

alias zshconfig="$EDITOR ~/.zshrc"
alias aliases="$EDITOR ~/.aliases"
alias gitconfig="$EDITOR ~/.gitconfig"
alias sshconfig="$EDITOR ~/.ssh/config"

alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
