#!/usr/bin/env bash

# ls

alias ls='ls --color=auto'
alias l='ls -lAh'

# xclip

alias xclip='xclip -selection clipboard'

# Config files

alias aliases="$EDITOR ~/.aliases"
alias envconfig="$EDITOR ~/.env"
alias zshconfig="$EDITOR ~/.zshrc"
alias gitconfig="$EDITOR ~/.gitconfig"
alias sshconfig="$EDITOR ~/.ssh/config"
alias npmconfig="$EDITOR ~/.npmrc"

# Misc

alias files='xdg-open . &> /dev/null'
alias newtab='gnome-terminal -q --tab'
# update-grub is already a command on some distros
[ $(command -v update-grub) ] || alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

# Docker

alias down='docker-compose down'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias stop='docker-compose stop'
alias up='docker-compose up -d'

# Git

alias ga='git add'
alias gaa='git add -A'
alias gb='git branch'
alias gbd='git branch -d'
alias gbdd='git branch -D'
alias gbr='git branch -r'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gl='git log'
alias gm='git merge'
alias gp='git push'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gr='git restore'
alias grb='git rebase'
alias grh='git reset --hard'
alias gs='git status'
alias gsw='git switch'
alias gswc='git switch -c'
alias gt='git tag'
