#!/bin/bash

# ls

alias ls='ls --color=auto'
alias l='ls -lAh'

# Config files

alias zshconfig="$EDITOR ~/.zshrc"
alias aliases="$EDITOR ~/.aliases"
alias gitconfig="$EDITOR ~/.gitconfig"
alias sshconfig="$EDITOR ~/.ssh/config"

# Misc

alias files='xdg-open . &> /dev/null'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias newtab='gnome-terminal -q --tab'

# Docker

alias up='docker-compose up -d'
alias down='docker-compose down'
