#!/bin/zsh

# ZLE docs: https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html

# To create a widget from a function:
# zle -N function-name{,}
# This creates a ZLE widget with the same name as the function.

# F1
bindkey '^[OP' run-help

# F2
function run-explain() {
    if [ -n "$BUFFER" ]
    then
        echo
        explain "$BUFFER"
        zle redisplay
    fi
}
zle -N run-explain{,}
bindkey '^[OQ' run-explain

# F3
function run-tldr() {
    local cmd
    cmd="$(echo "$BUFFER" | head -n1 | awk '{print $1;}')"
    if [ -n "$cmd" ]
    then
        tldr "$cmd"
        zle redisplay
    fi
}
zle -N run-tldr{,}
bindkey '^[OR' run-tldr

# ctrl+backspace
bindkey '^H' backward-delete-word
