# SSH agent setup.
# Based on: https://stackoverflow.com/a/18915067

SSH_ENV="$HOME/.ssh/agent_env"

function startSshAgent
{
	ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
	source "${SSH_ENV}"
}

if [ -f "${SSH_ENV}" ]
then
	source "${SSH_ENV}"
	ps "$SSH_AGENT_PID" > /dev/null || startSshAgent
else
	startSshAgent
fi
