#!/bin/zsh

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. (~/.oh-my-zsh/themes/ and ~/.oh-my-zsh/custom/themes/)
ZSH_THEME="spaceship"

# Set the plugins to load. (~/.oh-my-zsh/plugins/ and ~/.oh-my-zsh/custom/plugins/)
plugins=(
	thefuck
	git
	sudo
	mvn
	web-search
)

# Theme configuration.

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL=

# User configuration.

source "$ZSH/oh-my-zsh.sh"
numlockx on

# Environment variables.

BROWSER="/usr/bin/firefox"

if [ $(command -v go) ]
then
	export GOPATH="$HOME/Projects/go"
	eval $(go env | sed "s/^/export /")
	export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
fi

if [ -d "$HOME/bin" ]
then
	export PATH="$PATH:$HOME/bin"
fi

# Aliases.

alias zshconfig="nano ~/.zshrc"
alias files="xdg-open ."
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
