#!/bin/zsh

# Options
setopt nobeep

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. (~/.oh-my-zsh/themes/ and ~/.oh-my-zsh/custom/themes/)
ZSH_THEME="gokart"

# Set the plugins to load. (~/.oh-my-zsh/plugins/ and ~/.oh-my-zsh/custom/plugins/)
plugins=(
	thefuck
	sudo # Load sudo after thefuck, so it binds to the double-esc keybinding (which thefuck also does).
	docker
	docker-compose
)

# Load Oh My Zsh.
source "$ZSH/oh-my-zsh.sh"

# Load autocompletion and syntax highlighting.
autoload -Uz compinit colors
compinit
colors
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Autocompletion for specific folders.
zstyle -e ':completion:*' command-path 'reply=( "$PWD/.bin-luca" "$path[@]" )'

# User configuration.
source ~/.env
source ~/.aliases

# NVM
if [ -f '/usr/share/nvm/init-nvm.sh' ]
then
	source '/usr/share/nvm/init-nvm.sh'
fi

# PATH variable.

function addPath
{
	export PATH="$PATH:$1"
}

if [ $(command -v go) ]
then
	eval $(go env | sed "s/^/export /")
	addPath "$GOROOT/bin:$GOPATH/bin"
fi

if [ -d "$HOME/.local/share/gem/ruby/2.7.0/bin" ]
then
	addPath "$HOME/.local/share/gem/ruby/2.7.0/bin"
fi
