#!/bin/zsh

# Options
setopt nobeep

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. (~/.oh-my-zsh/themes/ and ~/.oh-my-zsh/custom/themes/)
ZSH_THEME="gokart"

# Set the plugins to load. (~/.oh-my-zsh/plugins/ and ~/.oh-my-zsh/custom/plugins/)
plugins=(
	sudo
	docker
	docker-compose
)

# Load Oh My Zsh.
source "$ZSH/oh-my-zsh.sh"

# Load autocompletion and syntax highlighting.
autoload -Uz compinit colors
compinit
colors
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# User configuration.
source ~/.env
source ~/.aliases

# Keybinds

# For more ZLE docs, see: https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html

# Bind F1 to run-help (man).
bindkey '^[OP' run-help

function run-explain() {
        echo
        explain "$BUFFER"
        zle redisplay
}
# Create a widget for the run-explain function with the same name.
zle -N run-explain{,}
# Bind F2 to run-explain.
bindkey '^[OQ' run-explain

# NVM
if [ -f '/usr/share/nvm/init-nvm.sh' ]
then
	source '/usr/share/nvm/init-nvm.sh'
fi

# PATH variable.

function addPath
{
	export PATH="$PATH:$1"
}

if [ $(command -v go) ]
then
	eval $(go env | sed "s/^/export /")
	addPath "$GOROOT/bin:$GOPATH/bin"
fi

if [ -d "$HOME/.local/share/gem/ruby/2.7.0/bin" ]
then
	addPath "$HOME/.local/share/gem/ruby/2.7.0/bin"
fi
